fix: Navbar2 to NabvaNews
Sstomi/zeteoh_test pull request #22
Opened 2023-04-09 01:12 UTC by Sstomi

2023-04-09 01:17 UTC, dhassault approved these changes
Good work! I just have a question, just for curiosity. Anyway thanks!

2023-04-09 01:17 UTC, dhassault commented on components/Footer.js
> +                  alt="zeteoh_logo"
Why replacing `-` by `_`? Is it important as `alt`?

2023-04-09 01:19 UTC, dhassault requested changes
[back-to-news-list](https://deploy-preview-22--zeteohai.netlify.app/news) is missing in the news post at the bottom.

2023-04-09 01:24 UTC, Sstomi commented on components/Footer.js
> +                  alt="zeteoh_logo"
It's for google.com

2023-04-10 02:04 UTC, dhassault approved these changes

2023-04-11 03:06 UTC, merged